### ISSUE TITLE
Cannot plot individual histogram signal files

### ISSUE THREAD

**Issue by kratsg** [awesome-workshop/awesome-htautau-analysis#8]
I cannot get `python plot.py hist_ggH.root hist_ggH.pdf` working out of the box as it complains about missing `qqH`. Can we get it updated to handle individual signals?

**Comment by stwunsch** [comment]
Hi! The plot combines all histograms in `histograms.root` to a single plot, so you need always all of them. Is this an issue for you?

**Comment by kratsg** [comment]
Yes. `histogram.py` can run on a signal file only -- and we want to test the functionality of `plot.py` in a CI job which means running it pretty lean.

**Comment by stwunsch** [comment]
Plotting without a bunch of histograms does not really make sense. I don't fully understand how I could help!

**Comment by stwunsch** [comment]
You can just make a `hist.Draw()` in a minimal python script, if this helps?

**Comment by kratsg** [comment]
Why can't the script adapt to choose which samples to draw? Especially if we can keep the same format?

**Comment by stwunsch** [comment]
because we squash together the information from a mixture of the inputs to make a (physics wise) meaningful plot! it's not simple to remove something there, e.g., we use all MC contributions to estimate QCD via the sideband extrapolation.

**Comment by kratsg** [comment]
Hi, just an FYI but this is a minor annoyance for Day 2 of the workshop. Producing the entire histograms.root file is not so easily possible, and it would be nice to have individual sample histograms made to pass around for plotting.

**Comment by stwunsch** [comment]
Thanks, good to know! And you can produce only the histograms for a single sample (it's called `histograms_ggH.root` or so), but to make a meaningful plot (physics wise), you need all contributions. So the question is simply what you want to do. If you just want to process a single sample and have a look a single histogram, it's ofc possible. If you want a full physics plot, then not.
